name: Create release from tag

on:
  push:
    tags:
      - "v3*"

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "release"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      #- name: Set up JDK 17
      #  uses: actions/setup-java@v3
      #  with:
      #    java-version: "17"
      #    distribution: "adopt"

      - uses: actions/checkout@v4
        with:
          ref: hub
          sparse-checkout: .
          sparse-checkout-cone-mode: false

      - name: Scala to JS
        # run: ./mill js.fullLinkJS
        run: touch main.js
        
      - uses: olegtarasov/get-tag@v2.1.2
        id: tagName
        
      - name: Rename JS File to Release Name 
        run: | 
          mkdir ${{steps.tagName.outputs.tag}}
          mv main.js  ${{steps.tagName.outputs.tag}}/${{steps.tagName.outputs.tag}}.js


          
      - name: Update the releases file
        run: |
          python update.py info.json ${{steps.tagName.outputs.tag}}
          
      - uses: stefanzweifel/git-auto-commit-action@v5
      
