name: Create release from tag

on:
  push:
    tags:
      - "v3*"

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      #- name: Set up JDK 17
      #  uses: actions/setup-java@v3
      #  with:
      #    java-version: "17"
      #    distribution: "adopt"

      - name: Scala to JS
        # run: ./mill js.fullLinkJS
        run: touch main.js
        
      - uses: olegtarasov/get-tag@v2.1.2
        id: tagName
        
      - name: Rename JS File to Release Name 
        run: | 
          mv main.js ${{steps.tagName.outputs.tag}}.js

      - uses: actions/checkout@v4
        with:
          ref: hub
          
      - name: Stage Changes
        run: git add .
        
      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Push the thing lol"
