name: Create release from tag

on:
  repository_dispatch:
    types: [vyxal3-release]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "release"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      #- name: Set up JDK 17
      #  uses: actions/setup-java@v3
      #  with:
      #    java-version: "17"
      #    distribution: "adopt"
          
      - uses: actions/checkout@v4
        with:
          ref: hub

        
      - uses: olegtarasov/get-tag@v2.1.2
        id: tagName
        
      - name: Download files to release folder
        run: | 
          echo "${{github.event.client_payload}}"
          python -m pip install --upgrade pip
          python -m pip install requests
          mkdir ${{github.event.client_payload.tag}}
          git clone https://github.com/Vyxal/vyxal.github.io.git ${{github.event.client_payload.tag}}
          python file_funcs.py "${{github.event.client_payload.files}}" ${{github.event.client_payload.tag}}
          cd ${{github.event.client_payload.tag}}
          rm -rfd .git
          
          
      - uses: stefanzweifel/git-auto-commit-action@v5
      
